name: vendor
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.1+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  image_picker: ^0.8.3+3
  google_sign_in: ^5.0.5
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  auto_size_text: ^2.1.0
  google_fonts: ^2.1.0
  get: ^3.25.4

  intl: 
  flutter_icons: ^1.1.0 
  font_awesome_flutter: ^9.1.0 
  flutter_svg: ^0.22.0 
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  path_provider: ^2.0.2 
  lottie: ^1.0.1
  persistent_bottom_nav_bar: 4.0.2 
  salomon_bottom_bar: 3.1.0 
  connectivity: ^3.0.6 
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  firebase_analytics: ^8.2.0
  admob_flutter: ^1.0.1
  flutter_native_admob: ^2.1.0+3



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family:  Cupon_Sale
      fonts:
       - asset: assets/icons/fonts/Cupon_Sale.ttf
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/Roboto/Roboto-Black.ttf
  uses-material-design: true
  assets:
    - images/
    - assets/
    - assets/jsons_Animation/
    - assets/jsons_Animation/landingpage/
    - assets/images/
    - assets/icons/fonts/
