/// Flutter icons Cupon_Sale
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
// flutter:
//   fonts:
//    - family:  Cupon_Sale
//      fonts:
//       - asset: fonts/Cupon_Sale.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Cupon_Sale {
  Cupon_Sale._();

  static const _kFontFam = 'Cupon_Sale';
  static const String _kFontPkg = null;

  static const IconData coupon1 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sale =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sale_tag =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coupon =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discount =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cotton_pad =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_stories =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
